/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MembershipsIndexRouteImport } from './routes/memberships/index'
import { Route as MembershipsNewRouteImport } from './routes/memberships/new'
import { Route as MembershipsMembershipsIdRouteImport } from './routes/memberships/$membershipsId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MembershipsIndexRoute = MembershipsIndexRouteImport.update({
  id: '/memberships/',
  path: '/memberships/',
  getParentRoute: () => rootRouteImport,
} as any)
const MembershipsNewRoute = MembershipsNewRouteImport.update({
  id: '/memberships/new',
  path: '/memberships/new',
  getParentRoute: () => rootRouteImport,
} as any)
const MembershipsMembershipsIdRoute =
  MembershipsMembershipsIdRouteImport.update({
    id: '/memberships/$membershipsId',
    path: '/memberships/$membershipsId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/memberships/$membershipsId': typeof MembershipsMembershipsIdRoute
  '/memberships/new': typeof MembershipsNewRoute
  '/memberships': typeof MembershipsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/memberships/$membershipsId': typeof MembershipsMembershipsIdRoute
  '/memberships/new': typeof MembershipsNewRoute
  '/memberships': typeof MembershipsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/memberships/$membershipsId': typeof MembershipsMembershipsIdRoute
  '/memberships/new': typeof MembershipsNewRoute
  '/memberships/': typeof MembershipsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/memberships/$membershipsId'
    | '/memberships/new'
    | '/memberships'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/memberships/$membershipsId'
    | '/memberships/new'
    | '/memberships'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/memberships/$membershipsId'
    | '/memberships/new'
    | '/memberships/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  MembershipsMembershipsIdRoute: typeof MembershipsMembershipsIdRoute
  MembershipsNewRoute: typeof MembershipsNewRoute
  MembershipsIndexRoute: typeof MembershipsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/memberships/': {
      id: '/memberships/'
      path: '/memberships'
      fullPath: '/memberships'
      preLoaderRoute: typeof MembershipsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/memberships/new': {
      id: '/memberships/new'
      path: '/memberships/new'
      fullPath: '/memberships/new'
      preLoaderRoute: typeof MembershipsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/memberships/$membershipsId': {
      id: '/memberships/$membershipsId'
      path: '/memberships/$membershipsId'
      fullPath: '/memberships/$membershipsId'
      preLoaderRoute: typeof MembershipsMembershipsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  MembershipsMembershipsIdRoute: MembershipsMembershipsIdRoute,
  MembershipsNewRoute: MembershipsNewRoute,
  MembershipsIndexRoute: MembershipsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
